track_list = [
    {"artist": "Real McCoy", "title": "Another Night", "genre": "pop"},
    {"artist": "Lifehouse", "title": "Hanging By A Moment", "genre": "pop"},
    {"artist": "Nickelback", "title": "How You Remind Me", "genre": "pop"},
    {"artist": "3 Doors Down", "title": "Here Without You", "genre": "pop"},
    {"artist": "No Doubt", "title": "Don't Speak", "genre": "pop"},
    {"artist": "Goo Goo Dolls", "title": "Iris", "genre": "pop"},
    {"artist": "Donna Lewis", "title": "I Love You Always Forever", "genre": "pop"},
    {"artist": "Maroon 5", "title": "One More Night", "genre": "pop"},
    {"artist": "Avicii", "title": "Wake Me Up!", "genre": "pop"},
    {"artist": "Ke$ha", "title": "TiK ToK", "genre": "pop"},
    {"artist": "Goo Goo Dolls", "title": "Slide", "genre": "pop"},
    {"artist": "Goo Goo Dolls", "title": "Name", "genre": "pop"},
    {"artist": "OneRepublic", "title": "Counting Stars", "genre": "pop"},
    {"artist": "Spin Doctors", "title": "Two Princes", "genre": "pop"},
    {"artist": "Bruno Mars", "title": "Locked Out of Heaven", "genre": "pop"},
    {"artist": "Savage Garden", "title": "Truly Madly Deeply", "genre": "pop"},
    {"artist": "3 Doors Down", "title": "Kryptonite", "genre": "pop"},
    {"artist": "Kelly Clarkson", "title": "Since U Been Gone", "genre": "pop"},
    {"artist": "Britney Spears", "title": "...Baby One More Time", "genre": "pop"},
    {"artist": "Kelly Clarkson", "title": "Because Of You", "genre": "pop"},
    {"artist": "The Black Eyed Peas", "title": "Where Is The Love?", "genre": "pop"},
    {"artist": "Ed Sheeran", "title": "Shape Of You", "genre": "pop"},
    {"artist": "Jewel", "title": "You Were Meant For Me", "genre": "pop"},
    {"artist": "Creed", "title": "With Arms Wide Open", "genre": "pop"},
    {"artist": "Bruno Mars", "title": "Just The Way You Are", "genre": "pop"},

    {"artist": "Florida Georgia Line", "title": "Cruise", "genre": "country"},
    {"artist": "Leroy Van Dyke", "title": "Walk On By", "genre": "country"},
    {"artist": "Hunter Hayes", "title": "Wanted", "genre": "country"},
    {"artist": "Sam Hunt", "title": "Take Your Time", "genre": "country"},
    {"artist": "Jack Greene", "title": "There Goes My Everything", "genre": "country"},
    {"artist": "Buck Owens", "title": "Love's Gonna Live Here", "genre": "country"},
    {"artist": "C.W. McCall", "title": "Convoy", "genre": "country"},
    {"artist": "Keith Urban", "title": "Somebody Like You", "genre": "country"},
    {"artist": "Lonestar", "title": "Amazed", "genre": "country"},
    {"artist": "Johnny Cash", "title": "Daddy Sang Bass", "genre": "country"},
    {"artist": "Charley Pride", "title": "Kiss An Angel Good Mornin'", "genre": "country"},
    {"artist": "Tim McGraw", "title": "Just To See You Smile", "genre": "country"},
    {"artist": "Connie Smith", "title": "Once A Day", "genre": "country"},
    {"artist": "Lady Antebellum", "title": "Need You Now", "genre": "country"},
    {"artist": "Tim McGraw", "title": "Live Like You Were Dying", "genre": "country"},
    {"artist": "Waylon Jennings", "title": "Luckenbach, Texas (Back To The Basics Of Love)", "genre": "country"},
    {"artist": "Mark Wills", "title": "19 Somethin'", "genre": "country"},
    {"artist": "Freddie Hart", "title": "My Hang-Up Is You", "genre": "country"},
    {"artist": "George Strait", "title": "Check Yes Or No", "genre": "country"},
    {"artist": "Glen Campbell", "title": "Rhinestone Cowboy", "genre": "country"},
    {"artist": "Toby Keith", "title": "How Do You Like Me Now?!", "genre": "country"},
    {"artist": "Dolly Parton", "title": "Here You Come Again", "genre": "country"},
    {"artist": "Rodney Atkins", "title": "If You're Going Through Hell (Before The Devil Even Knows)", "genre": "country"},
    {"artist": "Alan Jackson", "title": "Chattahoochee", "genre": "country"},
    {"artist": "The Judds", "title": "Have Mercy", "genre": "country"},

    {"artist": "Mary J. Blige", "title": "Be Without You", "genre": "hip hop"},
    {"artist": "Usher", "title": "You Make Me Wanna...", "genre": "hip hop"},
    {"artist": "Marvin Gaye", "title": "Sexual Healing", "genre": "hip hop"},
    {"artist": "Deborah Cox", "title": "Nobody's Supposed To Be Here", "genre": "hip hop"},
    {"artist": "Whitney Houston", "title": "I Will Always Love You", "genre": "hip hop"},
    {"artist": "Maxwell", "title": "Pretty Wings", "genre": "hip hop"},
    {"artist": "Al Green", "title": "Let's Stay Together", "genre": "hip hop"},
    {"artist": "The Weeknd", "title": "The Hills", "genre": "hip hop"},
    {"artist": "Mariah Carey", "title": "We Belong Together", "genre": "hip hop"},
    {"artist": "Chubby Checker", "title": "The Twist", "genre": "hip hop"},
    {"artist": "Maxwell", "title": "Fortunate", "genre": "hip hop"},
    {"artist": "Next", "title": "Too Close", "genre": "hip hop"},
    {"artist": "Stevie Wonder", "title": "That Girl", "genre": "hip hop"},
    {"artist": "Bobby Lewis", "title": "Tossin' And Turnin'", "genre": "hip hop"},
    {"artist": "Mario", "title": "Let Me Love You", "genre": "hip hop"},
    {"artist": "TLC", "title": "Creep", "genre": "hip hop"},
    {"artist": "Donell Jones", "title": "U Know What's Up", "genre": "hip hop"},
    {"artist": "Prince", "title": "When Doves Cry", "genre": "hip hop"},
    {"artist": "Monica", "title": "Before You Walk Out Of My Life/Like This And Like That", "genre": "hip hop"},
    {"artist": "Karyn White", "title": "Superwoman", "genre": "hip hop"},
    {"artist": "The Marvelettes", "title": "Please Mr. Postman", "genre": "hip hop"},
    {"artist": "Keyshia Cole", "title": "Heaven Sent", "genre": "hip hop"},
    {"artist": "Pharrell Williams", "title": "Happy", "genre": "hip hop"},
    {"artist": "Ray Charles", "title": "I Can't Stop Loving You", "genre": "hip hop"},
    {"artist": "Robin Thicke", "title": "Lost Without U", "genre": "hip hop"},

    {"artist": "Led Zeppelin", "title": "Stairway To Heaven", "genre": "rock"},
    {"artist": "The Yesteryears", "title": "Hey Jude", "genre": "rock"},
    {"artist": "Lynyrd Skynyrd", "title": "Sweet Home Alabama", "genre": "rock"},
    {"artist": "Bruce Springsteen", "title": "Born to Run", "genre": "rock"}, 
    {"artist": "Aerosmith", "title": "Dream On", "genre": "rock"}, 
    {"artist": "Eagles", "title": "Hotel California - Remastered", "genre": "rock"}, 
    {"artist": "Queen", "title": "Bohemian Rhapsody", "genre": "rock"},
    {"artist": "The Who", "title": "Won't Get Fooled Again", "genre": "rock"},
    {"artist": "The Yesteryears", "title": "Let It Be", "genre": "rock"},
    {"artist": "Boston", "title": "More Than a Feeling", "genre": "rock"},
    {"artist": "Pink Floyd", "title": "Another Brick in the Wall, Pt. 2", "genre": "rock"},
    {"artist": "Studio 99", "title": "Imagine", "genre": "rock"},
    {"artist": "The Rolling Stones", "title": "(I Can't Get No) Satisfaction", "genre": "rock"},
    {"artist": "Queen", "title": "We Will Rock You", "genre": "rock"},
    {"artist": "Lynyrd Skynyrd", "title": "Free Bird", "genre": "rock"},
    {"artist": "Led Zeppelin", "title": "Black Dog", "genre": "rock"}, 
    {"artist": "Pink Floyd", "title": "Wish You Were Here", "genre": "rock"},
    {"artist": "Steve Miller", "title": "The Joker", "genre": "rock"},
    {"artist": "The Rolling Stones", "title": "Sympathy For The Devil", "genre": "rock"},
    {"artist": "Thunderstruck", "title": "You Shook Me All Night Long", "genre": "rock"},
    {"artist": "The Rolling Stones", "title": "Gimme Shelter", "genre": "rock"},
    {"artist": "Billy Joel", "title": "Piano Man", "genre": "rock"},
    {"artist": "The Doors", "title": "Light My Fire", "genre": "rock"},
    {"artist": "Jimmy Buffett", "title": "Margaritaville", "genre": "rock"},
    {"artist": "The Who", "title": "Baba O'Riley", "genre": "rock"}, 

    {"artist": "Muse", "title": "Uprising", "genre": "alternative"},
    {"artist": "Rise Against", "title": "Savior", "genre": "alternative"}, 
    {"artist": "Muse", "title": "Madness", "genre": "alternative"},
    {"artist": "Foo Fighters", "title": "The Pretender", "genre": "alternative"}, 
    {"artist": "Imagine Dragons", "title": "Radioactive", "genre": "alternative"}, 
    {"artist": "Fuel", "title": "Hemorrhage (In My Hands)", "genre": "alternative"}, 
    {"artist": "Peter Murphy", "title": "Cuts You Up", "genre": "alternative"}, 
    {"artist": "Incubus", "title": "Drive", "genre": "alternative"}, 
    {"artist": "Marcy Playground", "title": "Sex And Candy", "genre": "alternative"}, 
    {"artist": "Green Day", "title": "When I Come Around", "genre": "alternative"}, 
    {"artist": "Lit", "title": "My Own Worst Enemy", "genre": "alternative"},
    {"artist": "Live", "title": "Lightning Crashes", "genre": "alternative"}, 
    {"artist": "Oasis", "title": "Wonderwall", "genre": "alternative"}, 
    {"artist": "Staind", "title": "It's Been Awhile", "genre": "alternative"},
    {"artist": "Nirvana", "title": "Smells Like Teen Spirit", "genre": "alternative"},
    {"artist": "Green Day", "title": "Boulevard Of Broken Dreams", "genre": "alternative"},
    {"artist": "Gorillaz", "title": "Feel Good Inc", "genre": "alternative"},
    {"artist": "Love and Rockets", "title": "So Alive", "genre": "alternative"}, 
    {"artist": "U2", "title": "Mysterious Ways", "genre": "alternative"},
    {"artist": "New Order", "title": "Regret", "genre": "alternative"},
    {"artist": "The Black Keys", "title": "Tighten Up", "genre": "alternative"}, 
    {"artist": "Puddle Of Mudd", "title": "Blurry", "genre": "alternative"},
    {"artist": "Foster The People", "title": "Pumped Up Kicks", "genre": "alternative"}, 
    {"artist": "Linkin Park", "title": "In The End", "genre": "alternative"},
    {"artist": "Phoenix", "title": "1901", "genre": "alternative"}
]